const form = document.getElementById("goalForm");
const resultDiv = document.getElementById("result");

form.addEventListener("submit", async (e) => {
  e.preventDefault();

  // Parse inputs from the form
  const income = parseFloat(document.getElementById("income").value);
  const savings = parseFloat(document.getElementById("savings").value);
  const goal = document.getElementById("goal").value.trim();
  const targetAmount = parseFloat(document.getElementById("targetAmount").value);
  const timeFrame = parseFloat(document.getElementById("timeFrame").value);

  resultDiv.style.display = "block";
  resultDiv.innerHTML = "🔄 Generating your AI plan...";

  // 👉 UPDATED URL: Points to the Flask server running on port 5000
  const backendURL = "http://http://127.0.0.1:5500/api/plan"; 

  try {
    const res = await fetch(backendURL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        income,
        savings,
        goal,
        targetAmount,
        timeFrame,
      }),
    });

    if (!res.ok) {
        const errorData = await res.json().catch(() => ({ error: "Unknown server error." }));
        throw new Error(`Backend error: ${errorData.error || res.statusText}`);
    }

    const data = await res.json();
    // Use innerHTML to allow for the rich formatting (like **bold**) generated by Python
    resultDiv.innerHTML = `<strong>💡 Your AI Budget Plan:</strong><br><br>${data.plan}`;
  } catch (error) {
    console.error(error);
    resultDiv.innerHTML =
      `❌ Could not connect to the AI server. Details: ${error.message}.`;
  }
});
